name: My test
inputs:
  var1:
    required: true
    type: string
  var2:
    required: true
    type: string
  var3:
    required: false
    type: string
    default: ''
    
runs:
  using: "composite"
  steps:
    - name: define
      id: path-definer
      shell: bash
      run: echo 'result-path=${{ inputs.var1 }}/${{ inputs.var2 }}' >> $GITHUB_OUTPUT
  
  
    - name: Result
      shell: bash
      run: echo "path: ${{ steps.path-definer.outputs.result-path }}"
