name: Artifacts cleanup
on:
  workflow_dispatch:

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          expire-in: 7days # Set this to 0 to delete all artifacts
