name: "Build solution"

on:
  workflow_dispatch:

jobs:

  #build:
  check:
    runs-on: windows-latest
    env: 
      dotnet-version: '7.0.x'
      wasm-project: 'Uno.App/Uno.App/Uno.App.Wasm/Uno.App.Wasm.csproj'
      android-project: 'Uno.App/Uno.App/Uno.App.Mobile/Uno.App.Mobile.csproj'
      ios-project: 'Uno.App/Uno.App/Uno.App.Mobile/Uno.App.Mobile.csproj'
      mac-project: 'Uno.App/Uno.App/Uno.App.Mobile/Uno.App.Mobile.csproj'
      gtk-project: 'Uno.App/Uno.App/Uno.App.Skia.Gtk/Uno.App.Skia.Gtk.csproj'
      win-project: 'Uno.App/Uno.App/Uno.App.Windows/Uno.App.Windows.csproj'
      configuration: Debug
      #uno-check-version: '1.11.2'
      #uno-check-manifest: 'https://raw.githubusercontent.com/unoplatform/uno.check/8f116f7fe73eb4ed527670a1738695e6f3da8856/manifests/uno.ui.manifest.json'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnet-version }}
        
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup the Uno Platform
      uses: ./.github/actions/setup-uno-platform
      
    - name: Build Windows
      uses: ./.github/actions/build-uno-project
      with:
        project-file: ${{ env.win-project }}
        project-configuration: ${{ env.configuration }}
        build-properties: -property:Platform=x64
        builder-type: msbuild
   
    - name: Build Wasm
      uses: ./.github/actions/build-uno-project
      with:
        project-file: ${{ env.wasm-project }}
        project-configuration: ${{ env.configuration }}
        builder-type: dotnet
      
    - name: Build Android
      uses: ./.github/actions/build-uno-project
      with:
        project-file: ${{ env.android-project }}
        project-configuration: ${{ env.configuration }}
        build-properties: -property:TargetFramework=net7.0-android
        builder-type: dotnet      
     
    - name: Build iOS
      uses: ./.github/actions/build-uno-project
      with:
        project-file: ${{ env.ios-project }}
        project-configuration: ${{ env.configuration }}
        build-properties: -property:TargetFramework=net7.0-ios
        builder-type: dotnet       
 
    - name: Build MacOS
      uses: ./.github/actions/build-uno-project
      with:
        project-file: ${{ env.mac-project }}
        project-configuration: ${{ env.configuration }}
        build-properties: -property:TargetFramework=net7.0-maccatalyst
        builder-type: dotnet  
      
    - name: Build GTK
      uses: ./.github/actions/build-uno-project
      with:
        project-file: ${{ env.mac-project }}
        project-configuration: ${{ env.configuration }}
        build-properties: -property:Platform=x64
        builder-type: dotnet
