name: "Uno-project check"

on:
  workflow_dispatch:

jobs:

  #build:
  check:
    runs-on: windows-latest
    env: 
      dotnet-version: '7.0.x'
      wasm-project: 'Uno.App/Uno.App/Uno.App.Wasm/Uno.App.Wasm.csproj'
      android-project: 'Uno.App/Uno.App/Uno.App.Mobile/Uno.App.Mobile.csproj'
      ios-project: 'Uno.App/Uno.App/Uno.App.Mobile/Uno.App.Mobile.csproj'
      mac-project: 'Uno.App/Uno.App/Uno.App.Mobile/Uno.App.Mobile.csproj'
      gtk-project: 'Uno.App/Uno.App/Uno.App.Skia.Gtk/Uno.App.Skia.Gtk.csproj'
      win-project: 'Uno.App/Uno.App/Uno.App.Windows/Uno.App.Windows.csproj'
      configuration: Debug
      #uno-check-version: '1.11.2'
      #uno-check-manifest: 'https://raw.githubusercontent.com/unoplatform/uno.check/8f116f7fe73eb4ed527670a1738695e6f3da8856/manifests/uno.ui.manifest.json'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
    
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnet-version }}
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2    
      
    - name: Update uno.check
      run: dotnet tool update --global uno.check --add-source https://api.nuget.org/v3/index.json
    
    - name: Run uno.check
      run: uno-check -v --ci --non-interactive --fix --skip androidsdk --skip androidemulator --skip xcode --skip gtk3 --skip vswin --skip vsmac
   
    - name: Build Windows
      run: msbuild ${{ env.win-project }} /r /p:Configuration=${{ env.configuration }} -p:Platform=x64 
   
    - name: Build Wasm
      run: dotnet build ${{ env.wasm-project }} -c ${{ env.configuration }}
      
    - name: Build Android
      run: dotnet build ${{ env.android-project }} -c ${{ env.configuration }} -p:TargetFramework=net7.0-android 
      
    - name: Build iOS
      run: dotnet build ${{ env.ios-project }} -c ${{ env.configuration }} -p:TargetFramework=net7.0-ios 
      
    - name: Build Mac
      run: dotnet build ${{ env.mac-project }} -c ${{ env.configuration }} -p:TargetFramework=net7.0-maccatalyst 

    - name: Build GTK
      run: dotnet build ${{ env.gtk-project }} -c ${{ env.configuration }} -p:Platform=x64 
  
