name: "Uno-project check"

on:
  workflow_dispatch:

jobs:

  #build:
  check:
    runs-on: windows-latest
    env: 
      dotnet-ver: '7.0.x'
      #UnoCheck_Version: '1.11.2'
      #UnoCheck_Manifest: 'https://raw.githubusercontent.com/unoplatform/uno.check/8f116f7fe73eb4ed527670a1738695e6f3da8856/manifests/uno.ui.manifest.json'

    steps:
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnet-ver }}
        
    - name: Update uno.check
      shell: pwsh
      run: |
        & dotnet tool update --global uno.check --version ${{ env.UnoCheck_Version }} --add-source https://api.nuget.org/v3/index.json
    
    - name: Run uno.check
      shell: pwsh
      run: |
        & uno-check -v --ci --non-interactive --fix --skip androidsdk --skip androidemulator --skip xcode --skip gtk3 --skip vswin --skip vsmac
   
    
