name: "Build solution"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  configure:
    runs-on: ubuntu-latest
    env:
      name: Uno.App
      root-dirictory: Uno.App
      project-file-template: '{0}/{1}/{1}.{2}/{1}.{2}.csproj'  # root/name/name.target/name.target.csproj
    outputs:
      projects-map: ${{ steps.set-projects.outputs.result }}
    steps:
      - id: set-projects
        run: |
          result=$(cat << EOF
            {
              "solution":"${{ format('{0}/{1}.sln', env.root-dirictory, env.name) }}",
              "android":"${{ format(env.project-file-template, env.root-dirictory, env.name, 'Mobile') }}",
              "gtk":"${{ format(env.project-file-template, env.root-dirictory, env.name, 'Skia.Gtk') }}",
              "ios":"${{ format(env.project-file-template, env.root-dirictory, env.name, 'Mobile') }}",
              "macos":"${{ format(env.project-file-template, env.root-dirictory, env.name, 'Mobile') }}",
              "wasm":"${{ format(env.project-file-template, env.root-dirictory, env.name, 'Wasm') }}",
              "windows":"${{ format(env.project-file-template, env.root-dirictory, env.name, 'Windows') }}",
            }
          EOF
          )
          echo "result<<EOF" >> $GITHUB_OUTPUT
          echo "$result" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
  build:
    needs: configure
    runs-on: windows-latest
    
    strategy:
      matrix:
        configuration: [ Debug, Release ]
        target: [ android, gtk, ios, macos, wasm, win-x64, win-x86, win-arm64 ]

    env: 
      dotnet-version: '7.0.x'
      configuration: ${{ matrix.configuration }}
      target: ${{ matrix.target }}
      projects-map: ${{ needs.configure.outputs.projects-map }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnet-version }}
        
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup the Uno Platform
      uses: ./.github/actions/setup-uno-platform
      with:
        uno-check-version: '1.5.0'
        uno-manifest: 'https://raw.githubusercontent.com/unoplatform/uno.check/main/manifests/uno.ui.manifest.json'
      
    - name: Build
      uses: ./.github/actions/build-uno-project
      with:
        projects-map: ${{ env.projects-map }}
        configuration: ${{ env.configuration }}
        target: ${{ env.target }}
