name: "Build solution"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env: 
      dotnet-version: '7.0.x'
      solution-name: 'Uno.App'
      solution-root: 'Uno.App'
      configuration: Debug
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnet-version }}
        
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup the Uno Platform
      uses: ./.github/actions/setup-uno-platform
      
    - name: Build All
      uses: ./.github/actions/build-uno-project
      with:
        solution-name: ${{ env.solution-name }}
        solution-root: ${{ env.solution-root }}
        configuration: ${{ env.configuration }}
        target: 'default'
