name: Select jobs experiment

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  
jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      jobs: ${{ steps.jobs.outputs.jobs }}

    steps:
      - name: Define Colors
        id: jobs
        run: |
          echo 'jobs=["job-1", "ignore-job-2", "job-3"]' >> "$GITHUB_OUTPUT"    
          
  job-1:
    runs-on: ubuntu-latest
    needs: prepare-matrix
    if: matrix.jobs == "job-1"
    strategy:
      matrix:
        jobs: ${{ fromJSON(needs.prepare-matrix.outputs.jobs) }}
    steps:
      - name: job-1 process
        run: |
          echo 'job-1'

  job-2:
    runs-on: ubuntu-latest
    needs: prepare-matrix
    if: matrix.jobs == "job-2"
    strategy:
      matrix:
        jobs: ${{ fromJSON(needs.prepare-matrix.outputs.jobs) }}
    steps:
      - name: job-2 process
        run: |
          echo 'job-2'

  job-3:
    runs-on: ubuntu-latest
    needs: prepare-matrix
    if: matrix.jobs == "job-3"
    strategy:
      matrix:
        jobs: ${{ fromJSON(needs.prepare-matrix.outputs.jobs) }}
    steps:
      - name: job-3 process
        run: |
          echo 'job-3'
