name: Select jobs experiment

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  
jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      job-list: ${{ steps.jobs.outputs.list }}

    steps:
      - name: Define Jobs
        id: jobs
        run: |
          job_list='[{"name":"job-1","value":"--111--"}, {"name":"ignore-job","value":"---"}, {"name":"job-3","value":"--333--"}]'
          echo "$job_list"
          echo "list=$job_list" >> "$GITHUB_OUTPUT"

  job-0:
    runs-on: ubuntu-latest
    needs: prepare-matrix
    steps:
      - name: job-0 process
        run: |
          echo "${{ needs.prepare-matrix.outputs.job-list }}"

      - name: job-0 process
        run: |
          var1="${{ contains(fromJSON(needs.prepare-matrix.outputs.job-list).*.name, 'job-1') }}"
          var2="${{ contains(fromJSON(needs.prepare-matrix.outputs.job-list).*.name, 'job-3') }}"

          res=$(var1 AND var2)

          echo "res: $res"
          
  job-1:
    runs-on: ubuntu-latest
    needs: prepare-matrix
    if: ${{ contains(fromJSON(needs.prepare-matrix.outputs.job-list).*.name, 'job-1') }}
    steps:
      - name: job-1 process
        run: |
          echo 'job-1'

  job-2:
    runs-on: ubuntu-latest
    needs: prepare-matrix
    if: ${{ contains(fromJSON(needs.prepare-matrix.outputs.job-list).*.name, 'job-2') }}
    steps:
      - name: job-2 process
        run: |
          echo 'job-2'

  job-3:
    runs-on: ubuntu-latest
    needs: prepare-matrix
    if: ${{ contains(fromJSON(needs.prepare-matrix.outputs.job-list).*.name, 'job-3') }}
    steps:
      - name: job-3 process
        run: |
          echo 'job-3'
