---

name: Test string input

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
   inputs:
      multistring-value:
        type: string
        default: |
          'value1'
          'value2'
          'value3' 'value4'

jobs:

  verify-string_input:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        run: |
          echo "1: '${{ inputs.multistring-value }}'"
          echo "2: '${{ env.TEST_STRING_VALUE }}'"
          echo "3: '$TEST_STRING_VALUE'"
        env:
          TEST_STRING_VALUE: |
            value1
            value2
            value3 value4
