# This workflow will publish the project

name: Test2

on:
  workflow_dispatch:
    inputs:
      condition:
        default: "ok"

jobs:
  prepare:
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.set-up.outputs.status }}

    steps:
    - name: Prepare a strategy matrix
      id: set-up
      shell: bash
      run: |
        con="${{github.event.inputs.condition}}"
        if [[ "$con" == "ok" ]]; then
          echo "status=true" >> $GITHUB_OUTPUT
        else
          echo "status=false" >> $GITHUB_OUTPUT
          echo "fail"
        fi
    
  publish:
    needs: prepare
    if: needs.prepare.outputs.status == 'true'
    runs-on: ubuntu-latest
  
     
    steps:
    - run: echo ${{ needs.prepare.outputs.status }}
    
