name: "Test"

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      properties: ${{ steps.set-properties.outputs.properties }}
    steps:
      - id: set-matrix
        run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
        
      - id: set-properties
        run: |
          properties=$(cat << EOF
            {
              "prop1":"var1",
              "prop2":"var2"
            }
          EOF
          )
          echo "properties<<EOF" >> $GITHUB_OUTPUT
          echo "$properties" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - run: echo "matrix (${{ matrix.project }}; ${{ matrix.config }})"
      - run: echo "properties (${{ needs.job1.outputs.properties }})"
      - run: |
          object=${{ fromJSON(needs.job1.outputs.properties) }} 
          echo "${{object.prop1}}|${{object.prop2}}"

 
