---

name: Test setup dotnet

on: # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  checks:
    runs-on: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Print dotnet info
        run: |
          dotnet --info

      - name: Init dotnet dir
        run: |
          echo "DOTNET_INSTALL_DIR=${{ github.workspace }}/.dotnet" >> $GITHUB_ENV

      - name: Setup dotnet
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: 8.x

      - name: Print dotnet info
        run: |
          dotnet --info
