name: "Test"

on:
  workflow_dispatch:

jobs:
  test-win:
    runs-on: windows-latest
     
    steps:
    - name: Shell name
      run: echo "$SHELL"
      
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
      
    - name: My test
      uses: ./.github/actions/my-test
      with:
        var1: "a"
        var2: "b"
      
  test-ubuntu:
    runs-on: ubuntu-latest
     
    steps:
    - name: Shell name
      run: echo "$SHELL"
      
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive      
      
    - name: My test
      uses: ./.github/actions/my-test
      with:
        var1: "a"
        var2: "b"
        var3: "c"
      
  test-macos:
    runs-on: macos-latest
     
    steps:
    - name: Shell name
      run: echo "$SHELL"
      
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive      
      
    - name: My test
      uses: ./.github/actions/my-test
      with:
        var1: "a"
        var2: "b"
