name: "Test"

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      properties: ${{ steps.set-properties.outputs.properties }}
    steps:
      - id: set-matrix
        run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
        
      - id: set-properties
        run: |
          props=$(cat << END
            {
              "prop1":"var1",
              "prop2":"var2"
            }
          END
          )
          echo 'json $props'
          echo 'properties=$props' >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - run: echo "matrix (${{ matrix.project }}; ${{ matrix.config }})"
      - run: echo "properties (${{ needs.job1.outputs.properties }})"
      - run: echo "fromJSON(properties) ${{ fromJSON(needs.job1.outputs.properties).prop1 }}"

 
