name: "Test"

on:
  workflow_dispatch:

jobs:
  test-win:
    runs-on: windows-latest
     
    steps:
    - name: Shell name
      run: echo "$SHELL"
      
  test-ubuntu:
    runs-on: ubuntu-latest
     
    steps:
    - name: Shell name
      run: echo "$SHELL"
      
  test-macos:
    runs-on: macos-latest
     
    steps:
    - name: Shell name
      run: echo "$SHELL"
