name: "Test"

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - run: echo "(${{ matrix.project }}; ${{ matrix.config }})"

  test-win:
    runs-on: windows-latest
     
    steps:
    - name: Shell name
      run: echo "$SHELL"
      
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
      
    - name: My test
      uses: ./.github/actions/my-test
      with:
        var1: "a"
        var2: "b"
      
  test-ubuntu:
    runs-on: ubuntu-latest
     
    steps:
    - name: Shell name
      run: echo "$SHELL"
      
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive      
      
    - name: My test
      uses: ./.github/actions/my-test
      with:
        var1: "a"
        var2: "b"
        var3: "c"
      
  test-macos:
    runs-on: macos-latest
     
    steps:
    - name: Shell name
      run: echo "$SHELL"
      
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive      
      
    - name: My test
      uses: ./.github/actions/my-test
      with:
        var1: "a"
        var2: "b"
