name: Workflow dispatch input test

on:
  workflow_dispatch:
    inputs:
      boolean-var:
        required: true
        type: boolean
      string-var:
        required: true
        type: string
  pull_request:

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Print
      run: |
        echo "Boolean: ${{ inputs.boolean-var }}"
        echo "String: ${{ inputs.string-var }}"
        
    - if: ${{ inputs.boolean-var }}
      name: Check
      run: |
        echo "Boolean: ${{ inputs.boolean-var }}"
        echo "String: ${{ inputs.string-var }}"
