name: Workflow dispatch input test

on:
  workflow_dispatch:
    inputs:
      boolean-var:
        required: true
        type: boolean
      string-var:
        required: true
        type: string
  pull_request:

env:
  secret-var: ${{ secrets.SOME_SECRET }}
jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Print
      run: |
        echo "Boolean: ${{ inputs.boolean-var }}"
        echo "String: ${{ inputs.string-var }}"
        echo "Secret: ${{ inputs.secret-var }}"
        
    - if: ${{ env.secret-var != '' }}
      name: Check
      run: |
        echo "Boolean: ${{ inputs.boolean-var }}"
        echo "String: ${{ inputs.string-var }}"
        echo "Secret: ${{ inputs.secret-var }}"
        
    - if: ${{ (env.secret-var != '' || inputs.boolean-var }}
      name: Ignore Check 
      run: |
        echo "Boolean: ${{ inputs.boolean-var }}"
        echo "String: ${{ inputs.string-var }}"
        echo "Secret: ${{ inputs.secret-var }}"
